name = "project-payroll"
type = "javascript" # or "webpack" depending on your setup
account_id = "560de786ce7d3be60bae6ff119f192b03d4bd"
workers_dev = true
compatibility_date = "2024-11-05"

[build]
command = "npm run build"
[site]
bucket = "./dist"
entry-point = "./"
pages_build_output_dir = "./dist"

